### ISSUE TITLE
Disable copy , select, etc. 

### ISSUE THREAD

**Issue by dani2003** [myflashlab/webView-ANE#59]
How can I disable copy , paste and select, etc... functionality is shown by default when I press down in page html.

Thanks!

**Comment by myflashlab** [comment]
You need to check JS tutorials for these kind of tasks.

**Comment by dani2003** [comment]
Excuse me , but in java scripts you can not disabiltiare the longclick . Everyone says to do so :

webview.setOnLongClickListener(new OnLongClickListener() {
@Override
public boolean onLongClick(View v) {
return true;
}
});
webview.setLongClickable(false);

**Comment by myflashlab** [comment]
they're wrong! :)

try this in your css
```css
body {
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* Internet Explorer */
  -khtml-user-select: none; /* KHTML browsers (e.g. Konqueror) */
  -webkit-user-select: none; /* Chrome, Safari, and Opera */
  -webkit-touch-callout: none; /* Disable Android and iOS callouts*/
}
```
