### ISSUE TITLE
Embed custom font

### ISSUE THREAD

**Issue by developOPQA** [myflashlab/webView-ANE#79]
Hi, I'm trying to embed a hosted on my server font through CSS, in the browser works fine, but when tested in the application with WebView, the font does not work.

**Comment by myflashlab** [comment]
You are probably doing something wrong because we have already tested this feature and it's working fine on both Android and iOS. fonts will embed with no problem.

**Comment by developOPQA** [comment]
Hi, Could you show me how are you embedding the font in the css ?. I am doing it so, but it does not work.
`<style type="text/css">
  @font-face { font-family: Smooth; src: url('http://myDomain.com/font/Smooth.ttf'); } 
.selectItem h1{
    font-family: Smooth;
}
</style>`

**Comment by imalitavakoli** [comment]
Here is how you can embed a font in HTML:
```css
/* First embed the font */
@font-face
{
	font-family: MyFont;
	src: url(font.ttf);
}

/* Now use it */
body
{
	font-family: MyFont;
}
```

Here you can also read more about font embedding in HTML:
http://www.w3schools.com/css/css3_fonts.asp
